# Generated by Django 5.1.2 on 2024-11-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cost',
            field=models.FloatField(),
        ),
    ]
