# Generated by Django 5.1.2 on 2024-11-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_cost_alter_task_deadline_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
