# Generated by Django 5.1.2 on 2024-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Nome da Tarefa'),
        ),
    ]
